# Generated by Django 4.1.7 on 2023-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_number', models.CharField(max_length=300)),
                ('pro_category', models.CharField(max_length=50)),
                ('pro_description', models.CharField(max_length=400)),
                ('pro_price', models.BigIntegerField()),
                ('pro_quantity', models.BigIntegerField()),
                ('pro_image', models.ImageField(upload_to='seller/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
