# Generated by Django 4.1.7 on 2023-04-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0002_category'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecom_admin.category'),
        ),
    ]
