# Generated by Django 4.1.7 on 2023-03-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('e_mail', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('acc_holder', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('accNo', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='seller/')),
                ('ifsc', models.CharField(max_length=50)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending..', max_length=30)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
